/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCashFlowRouteImport } from './routes/_app/cash-flow'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDriversRouteImport } from './routes/_app/drivers'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppFreezersRouteImport } from './routes/_app/freezers'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppPriceTablesRouteImport } from './routes/_app/price-tables'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppWeekPlanRouteImport } from './routes/_app/week-plan'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppFreezersRoute = AppFreezersRouteImport.update({
  id: '/freezers',
  path: '/freezers',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceTablesRoute = AppPriceTablesRouteImport.update({
  id: '/price-tables',
  path: '/price-tables',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekPlanRoute = AppWeekPlanRouteImport.update({
  id: '/week-plan',
  path: '/week-plan',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fleet': typeof AppFleetRoute
  '/freezers': typeof AppFreezersRoute
  '/leads': typeof AppLeadsRoute
  '/orders': typeof AppOrdersRoute
  '/price-tables': typeof AppPriceTablesRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/routes': typeof AppRoutesRoute
  '/sales': typeof AppSalesRoute
  '/stock': typeof AppStockRoute
  '/week-plan': typeof AppWeekPlanRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fleet': typeof AppFleetRoute
  '/freezers': typeof AppFreezersRoute
  '/leads': typeof AppLeadsRoute
  '/orders': typeof AppOrdersRoute
  '/price-tables': typeof AppPriceTablesRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/routes': typeof AppRoutesRoute
  '/sales': typeof AppSalesRoute
  '/stock': typeof AppStockRoute
  '/week-plan': typeof AppWeekPlanRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/cash-flow': typeof AppCashFlowRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/freezers': typeof AppFreezersRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/price-tables': typeof AppPriceTablesRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/routes': typeof AppRoutesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/week-plan': typeof AppWeekPlanRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/cash-flow'
    | '/clients'
    | '/dashboard'
    | '/drivers'
    | '/financeiro'
    | '/fleet'
    | '/freezers'
    | '/leads'
    | '/orders'
    | '/price-tables'
    | '/products'
    | '/reports'
    | '/routes'
    | '/sales'
    | '/stock'
    | '/week-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/cash-flow'
    | '/clients'
    | '/dashboard'
    | '/drivers'
    | '/financeiro'
    | '/fleet'
    | '/freezers'
    | '/leads'
    | '/orders'
    | '/price-tables'
    | '/products'
    | '/reports'
    | '/routes'
    | '/sales'
    | '/stock'
    | '/week-plan'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/cash-flow'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/drivers'
    | '/_app/financeiro'
    | '/_app/fleet'
    | '/_app/freezers'
    | '/_app/leads'
    | '/_app/orders'
    | '/_app/price-tables'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/routes'
    | '/_app/sales'
    | '/_app/stock'
    | '/_app/week-plan'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-flow': {
      id: '/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/freezers': {
      id: '/_app/freezers'
      path: '/freezers'
      fullPath: '/freezers'
      preLoaderRoute: typeof AppFreezersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-tables': {
      id: '/_app/price-tables'
      path: '/price-tables'
      fullPath: '/price-tables'
      preLoaderRoute: typeof AppPriceTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week-plan': {
      id: '/_app/week-plan'
      path: '/week-plan'
      fullPath: '/week-plan'
      preLoaderRoute: typeof AppWeekPlanRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriversRoute: typeof AppDriversRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFleetRoute: typeof AppFleetRoute
  AppFreezersRoute: typeof AppFreezersRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPriceTablesRoute: typeof AppPriceTablesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppStockRoute: typeof AppStockRoute
  AppWeekPlanRoute: typeof AppWeekPlanRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDriversRoute: AppDriversRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFleetRoute: AppFleetRoute,
  AppFreezersRoute: AppFreezersRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPriceTablesRoute: AppPriceTablesRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppSalesRoute: AppSalesRoute,
  AppStockRoute: AppStockRoute,
  AppWeekPlanRoute: AppWeekPlanRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
