// Database type for external Supabase.
// Replace with your actual schema types generated by:
//   npx supabase gen types typescript --project-id <your-project-ref>
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
